name: First Workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye
        run: echo "goodbye !"
      - name: Print hello
        run: echo "welcome"
  secondjob:    
    needs: test  
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye
        run: echo "goodbye !"
      - name: Print hello
        run: echo "welcome"


